init_weights: ./KWS/here/checkpoints/epoch=14-step=1459.ckpt
model:
  _target_: src.models.resnet.BCResNets
  n_classes: ${len:${train_dataloader.dataset.idx_to_keyword}}
  base_c: 8

train_dataloader:
  _target_: torch.utils.data.DataLoader
  num_workers: 4
  batch_size: 100
  prefetch_factor: 1
  collate_fn: ${function:src.data.collator}
  shuffle: True
  dataset:
    _target_: src.data.SpotterDataset
    manifest_path: "./keyword-spotting-mipt-2023/train/manifest_train.csv"
    idx_to_keyword:
    - 'sber'
    - 'joy'
    - 'afina'
    - 'salut'
    - 'filler'
    transforms:
      - _target_: torchaudio.transforms.MelSpectrogram
        sample_rate: 16000
        n_fft: 512
        win_length: 400
        hop_length: 160
        n_mels: 40
      - _target_: src.data.SpecScaler

val_dataloader:
  _target_: torch.utils.data.DataLoader
  num_workers: ${train_dataloader.num_workers}
  batch_size: ${train_dataloader.batch_size}
  prefetch_factor: ${train_dataloader.prefetch_factor}
  collate_fn: ${train_dataloader.collate_fn}
  shuffle: False
  dataset:
    _target_: src.data.SpotterDataset
    manifest_path: "./keyword-spotting-mipt-2023/train/manifest_val.csv"
    idx_to_keyword: ${train_dataloader.dataset.idx_to_keyword}
    transforms:
      - ${getindex:${train_dataloader.dataset.transforms}, 0}
      - ${getindex:${train_dataloader.dataset.transforms}, -1}

predict_dataloader:
  _target_: torch.utils.data.DataLoader
  num_workers: 1
  batch_size: ${val_dataloader.batch_size}
  prefetch_factor: ${val_dataloader.prefetch_factor}
  collate_fn: ${val_dataloader.collate_fn}
  shuffle: False
  dataset:
    _target_: ${val_dataloader.dataset._target_}
    manifest_path: "./keyword-spotting-mipt-2023/test/manifest.csv"
    idx_to_keyword: ${val_dataloader.dataset.idx_to_keyword}
    transforms: ${val_dataloader.dataset.transforms}
    test: True

trainer:
  _target_: pytorch_lightning.Trainer
  val_check_interval: 0.5
  check_val_every_n_epoch: 1
  log_every_n_steps: 5
  precision: 32
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  accelerator: auto
  max_steps: 15000
  devices: 1

logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: .
  
optim:
  _target_: torch.optim.SGD
  lr: 0
  momentum: 0.1
  weight_decay: 1e-3

